title: AI Agents â€” Learn & Build
description: Practical documentation and tutorials for designing, building, and evaluating AI agents (LLMs, RAG, examples).

# Development server config, needed to load some of the content
webrick:
  headers:
    Access-Control-Allow-Origin: "*"

# Theme settings
site_author: Carlos Pereira Atencio
repo_url: "https://github.com/carlosperate/jekyll-theme-rtd"
edit_on_github: true
github_docs_folder: false
sticky_navigation: true
prev_next_buttons_location: both
search_enabled: true
hljs_style: github-gist
