title: AI Agents â€” Learn & Build
description: Practical documentation and tutorials for designing, building, and evaluating AI agents (LLMs, RAG, examples).
remote_theme: carlosperate/jekyll-theme-rtd

# Theme settings:
site_author: Carlos Pereira Atencio
repo_url: "https://github.com/carlosperate/jekyll-theme-rtd"
edit_on_github: true
github_docs_folder: true
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: true
hljs_style: github-gist
